#Create docker file for project php 8.1
FROM php:8.1-fpm-alpine
# Install system dependencies
RUN apk add --no-cache \
    $PHPIZE_DEPS \
    libzip-dev \
    libpng-dev \
    libjpeg-turbo-dev \
    libwebp-dev \
    freetype-dev \
    libxpm-dev \
    libxml2-dev \
    libxslt-dev \
    libmcrypt-dev \
    libmemcached-dev \
    libmemcached-libs \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \
    libmemcachedutil2 \
    libmemcached-libsasl \
    libmemcached-protocol \
    libmemcached-1.0 \

# Install PHP extensions
RUN docker-php-ext-install \
    pdo_mysql \
    zip \
    gd \
    exif \
    bcmath \
    soap \
    xsl \
    opcache \
    pcntl \
    sockets \
    intl \
    xmlrpc \
    mysqli \
    pdo \
    pdo_mysql \
    pdo_pgsql \
    pdo_sqlite \
    pgsql \
    sqlite3 \
    gettext \
    shmop \
    sysvmsg \
    sysvsem \
    sysvshm \
    wddx \
    xml \
    xmlreader \
    xmlwriter \
    xsl \
    zip \
    bz2 \
    calendar \
    ctype \
    curl \
    dom \
    fileinfo \
    ftp \
    gd \
    gettext \
    hash \
    iconv \
    json \
    mbstring \
    mysqli \
    mysqlnd \
    openssl \
    pcntl \
    pcre \
    PDO \
    pdo_mysql \
    pdo_pgsql \
    pdo_sqlite \
    pgsql \
    Phar \
    posix \
    readline \
    Reflection \
    session \
    SimpleXML \
    soap \
    sockets \
    sodium \
    SPL \
    sqlite3 \
    standard \
    tokenizer \
    xml \
    xmlreader \
    xmlwriter \
    xsl \
    Zend OPcache \
    zip \
    zlib \
    bcmath \
    exif \
    gettext \
    intl \
    mysqli \
    opcache \
    pcntl \
    pdo_mysql \
    pdo_pgsql \
    pdo_sqlite \
    pgsql \
    shmop \
    soap \
    sockets \
    sysvmsg \
    sysvsem \
    sysvshm \
    wddx \
    xml \
    xmlreader \
    xmlrpc \
    xmlwriter \
    xsl \
    zip \
    bz2 \
    calendar \
    ctype \
    curl \
    dom \
    fileinfo \
    ftp \
    gd \
    gettext \
    hash \
    iconv \
    json \
    mbstring \
    mysqli \
    mysqlnd \
    openssl \
    pcntl \
    pcre \
    PDO \
    pdo_mysql \
    pdo_pgsql \
    pdo_sqlite \
    pgsql \
    Phar \
    posix \
    readline \
    Reflection \
    session \
    SimpleXML \
    soap \
    sockets \
    sodium \
    SPL \
    sqlite3 \
    standard \
    tokenizer \
    xml \
    xmlreader \
    xmlrpc

# Install PECL extensions
RUN pecl install \
    memcached \
    redis \
    xdebug \
    && docker-php-ext-enable \
    memcached \
    redis \
    xdebug

